image: hashicorp/terraform:latest

stages:
  - init
  - validate
  - scan
  - plan
  - apply
  - destroy

terraform_init:
  stage: init
  script:
    - terraform init -input=false
  artifacts:
    paths:
      - .terraform
      - .terraform.lock.hcl
    expire_in: 1 hour

terraform_validate:
  stage: validate
  dependencies:
    - terraform_init
  script:
    - terraform validate

terraform_scan:
  stage: scan
  image: aquasec/trivy:latest
  script:
    - trivy fs --exit-code 1 --severity HIGH,CRITICAL --format json --output trivy-report.json .
  artifacts:
    paths:
      - trivy-report.json
    expire_in: 1 hour
  allow_failure: true

terraform_plan:
  stage: plan
  dependencies:
    - terraform_init
  script:
    - terraform plan -out=tfplan -input=false
  artifacts:
    paths:
      - tfplan
    expire_in: 1 hour

terraform_apply:
  stage: apply
  dependencies:
    - terraform_plan
  script:
    - terraform apply -input=false tfplan
  when: manual

terraform_destroy:
  stage: destroy
  dependencies:
    - terraform_init
  script:
    - terraform destroy -input=false -auto-approve
  when: manual
